index:
    path: /
    controller: App\Controller\ViewController::index

error_not_found:
    path: /error_not_found
    controller: App\Controller\ViewController::showNotFoundException

signup-form:
    path: /user/signup
    controller: App\Controller\ViewController::signUpUserForm

signin-form:
    path: /user/signin
    controller: App\Controller\ViewController::signInUserForm

signup:
    path: /signup
    controller: App\Controller\UserController::signUpUser

signin:
    path: /signin
    controller: App\Controller\UserController::signInUser

signout:
    path: /user/signout
    controller: App\Controller\UserController::signOutUser

show_menu:
    path: /menu
    controller: App\Controller\ViewController::showMenu

show_legend:
    path: /legend
    controller: App\Controller\ViewController::showLegend

show_first_level:
    path: /first-level
    controller: App\Controller\ViewController::showFirstLevel

show_second_level:
    path: /second-level
    controller: App\Controller\ViewController::showSecondLevel

show_third_level:
    path: /third-level
    controller: App\Controller\ViewController::showSecondLevel

show_win:
    path: /win
    controller: App\Controller\ViewController::showWin

show_lose:
    path: /lose
    controller: App\Controller\ViewController::showLose

choose_level:
    path: /choose-level
    controller: App\Controller\ViewController::showLevels

show_rating:
    path: /rating
    controller: App\Controller\ViewController::showRating

api_score:
    path: /api/score
    controller: App\Controller\ApiController::saveScore
    methods: POST

lobby:
    path: /lobby
    controller: App\Controller\LobbyController::index

create_lobby:
    path: /lobby/create
    controller: App\Controller\LobbyController::create

join_lobby:
    path: /lobby/join/{id}
    controller: App\Controller\LobbyController::join

game:
    path: /game/{id}
    controller: App\Controller\GameController::index