index:
    path: /
    controller: App\Controller\ViewController::index

error_not_found:
    path: /error_not_found
    controller: App\Controller\ViewController::showNotFoundException

signup-form:
    path: /user/signup
    controller: App\Controller\ViewController::signUpUserForm

signin-form:
    path: /user/signin
    controller: App\Controller\ViewController::signInUserForm

signup:
    path: /signup
    controller: App\Controller\UserController::signUpUser

signin:
    path: /signin
    controller: App\Controller\UserController::signInUser

signout:
    path: /user/signout
    controller: App\Controller\UserController::signOutUser

show_menu:
    path: /menu
    controller: App\Controller\ViewController::showMenu