<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFpTnuNc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFpTnuNc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFpTnuNc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFpTnuNc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFpTnuNc\App_KernelDevDebugContainer([
    'container.build_hash' => 'FpTnuNc',
    'container.build_id' => 'b6507618',
    'container.build_time' => 1719410599,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFpTnuNc');
