<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxvk7K2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxvk7K2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCxvk7K2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCxvk7K2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCxvk7K2\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cxvk7K2',
    'container.build_id' => '9c6b41b7',
    'container.build_time' => 1719418466,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxvk7K2');
