<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTB87Vm9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTB87Vm9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTB87Vm9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTB87Vm9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTB87Vm9\App_KernelDevDebugContainer([
    'container.build_hash' => 'TB87Vm9',
    'container.build_id' => '64e4f35b',
    'container.build_time' => 1719395543,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTB87Vm9');
